name: demo-2023-ecp-f2f
channels:
  - bioconda
  - conda-forge
dependencies:
  - bash_kernel=0.9.0
  - curl=7.87.0
  - jq=1.6
  - jupyterlab=3.6.1
  - pip=23.0
  - psutil=5.8.0
  - python=3.8.16
  - snakemake=7.21.0
  - pip:
      - git+https://github.com/athenarc/cwl-tes.git@8c65dd3979621539c61fecdaa79c9809504fb2f5
      - pip~=23.0
